[package]
name = "tibco-ems-operator"
version = "0.1.0"
authors = ["Jens Walter <jens@apimeister.com>"]
edition = "2018"

[dependencies]
kube = "0.40.0"
k8s-openapi = {version = "0.9.0", default-features = false, features = ["v1_17"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1.8"
