[package]
name = "tibco-ems-operator"
version = "0.4.0"
authors = ["Jens Walter <jens@apimeister.com>"]
edition = "2018"

[dependencies]
kube = { version = "0.57", default-features = true, features = ["rustls-tls"] }
k8s-openapi = { version = "0.12", default-features = false, features = ["v1_18"] }
kube-derive = "0.57"
schemars = { version = "0.8.0", features = ["chrono"] }
chrono = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
once_cell = "1.7"
hyper = { version = "0.14", features = ["full"] }
log = "0.4"
env_logger = "0.8"
tibco_ems = "0.3"
#tibco_ems = { path = "./tibco-ems-rs", version = "0.2.8"}
env-var = "1"
