[package]
name = "tibco-ems-operator"
version = "0.1.0"
authors = ["Jens Walter <jens@apimeister.com>"]
edition = "2018"

[dependencies]
kube = { version = "0.40.0", default-features = false, features = ["rustls-tls"] }
kube-runtime = { version = "0.40.0", default-features = false, features = ["rustls-tls"] }
k8s-openapi = { version = "0.9.0", default-features = false, features = ["v1_17"] }
kube-derive = "0.40.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1.8"
futures = "0.3.5"
tokio = { version = "0.2", features = ["full"] }