apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bridges.tibcoems.apimeister.com
spec:
  group: tibcoems.apimeister.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                source_type:
                  type: string
                source_name:
                  type: string
                target_type:
                  type: string
                target_name:
                  type: string
                selector:
                  type: string
  scope: Namespaced
  names:
    plural: bridges
    singular: bridge
    kind: Bridge