apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queues.tibcoems.apimeister.com
spec:
  group: tibcoems.apimeister.com
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                global:
                  type: boolean
                expiration:
                  type: integer
                  format: int32
                maxbytes:
                  type: integer
                  format: int32
                maxmsgs:
                  type: integer
                  format: int32
                maxRedelivery:
                  type: integer
                  format: int32
                overflowPolicy:
                  type: integer
                  format: int32
                prefetch:
                  type: integer
                  format: int32
                redeliveryDelay:
                  type: integer
                  format: int32
            status:
              type: object
              properties:
                pendingMessages:
                  type: integer
                  format: int64
                consumerCount:
                  type: integer
                  format: int32
      additionalPrinterColumns:
      - name: pending messages
        type: integer
        description: the number of pending messages
        jsonPath: .status.pendingMessages
      - name: consumer count
        type: integer
        description: the number of consumers
        jsonPath: .status.consumerCount
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: queues
    singular: queue
    kind: Queue