apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: topics.tibcoems.apimeister.com
spec:
  group: tibcoems.apimeister.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                expiration:
                  type: integer
                  format: int32
                name:
                  type: string
                global:
                  type: boolean
                maxbytes:
                  type: integer
                  format: int32
                maxmsgs:
                  type: integer
                  format: int32
                overflowPolicy:
                  type: integer
                  format: int32
                prefetch:
                  type: integer
                  format: int32
  scope: Namespaced
  names:
    plural: topics
    singular: topic
    kind: Topic