apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: topics.tibcoems.apimeister.com
spec:
  group: tibcoems.apimeister.com
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                expiration:
                  type: integer
                  format: int32
                name:
                  type: string
                global:
                  type: boolean
                maxbytes:
                  type: integer
                  format: int32
                maxmsgs:
                  type: integer
                  format: int32
                overflowPolicy:
                  type: integer
                  format: int32
                prefetch:
                  type: integer
                  format: int32
            status:
              type: object
              properties:
                pendingMessages:
                  type: integer
                  format: int64
                subscribers:
                  type: integer
                  format: int32
                durables:
                  type: integer
                  format: int32
      additionalPrinterColumns:
      - name: pending messages
        type: integer
        description: the number of pending messages
        jsonPath: .status.pendingMessages
      - name: subscriber count
        type: integer
        description: the number of subscribers
        jsonPath: .status.subscribers
      - name: durable count
        type: integer
        description: the number of durables
        jsonPath: .status.durables
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp

  scope: Namespaced
  names:
    plural: topics
    singular: topic
    kind: Topic