apiVersion: apps/v1
kind: Deployment
metadata:
  name: tibco-ems-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tibco-ems-operator
  template:
    metadata:
      labels:
        app: tibco-ems-operator
    spec:
      serviceAccountName: tibco-ems-operator-account
      containers:
      - name: tibco-ems-operator
        image: gcr.io/apimeister/tibco-ems-operator
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: kubernetes
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVER_URL
            valueFrom:
              secretKeyRef:
                name: esb
                key: serverUrl
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: esb
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: esb
                key: password