apiVersion: apps/v1
kind: Deployment
metadata:
  name: tibco-ems-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tibco-ems-operator
  template:
    metadata:
      labels:
        app: tibco-ems-operator
    spec:
      serviceAccountName: tibco-ems-operator-account
      containers:
      - name: tibco-ems-operator
        image: gcr.io/apimeister/tibco-ems-operator
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "20Mi"
            cpu: "100m"
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: kubernetes
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVER_URL
            valueFrom:
              secretKeyRef:
                name: tibco-ems-operator-secret
                key: serverUrl
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: tibco-ems-operator-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: tibco-ems-operator-secret
                key: password