apiVersion: v1
kind: ServiceAccount
metadata:
  name: tibco-ems-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tibco-ems-operator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tibco-ems-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tibco-ems-operator-role
subjects:
- kind: ServiceAccount
  name: tibco-ems-operator-account
