apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-app
    tibcoems.apimeister.com/scaling: "true"
    tibcoems.apimeister.com/queue.1: test.q
  name: sample-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: nginx
        env:
          - name: SERVER_URL
            valueFrom:
              secretKeyRef:
                name: tibco-ems-operator-secret
                key: serverUrl
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: tibco-ems-operator-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: tibco-ems-operator-secret
                key: password
