name: pr
on:
  workflow_dispatch:
  pull_request:
  # push:
  #   branches: [main]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install Rust
      run: rustup update stable
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all -- -D warnings
    - uses: taiki-e/install-action@nextest
    - name: Cargo Test
      run: cargo nextest run --no-fail-fast
    - name: Cargo build
      run: cargo build --features no_tibco_driver
    - name: merge
      if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
      run: |
        gh pr merge --merge $GITHUB_HEAD_REF
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
