name: pr
on:
  workflow_dispatch:
  pull_request:
  # push:
  #   branches: [main]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
- uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt,clippy
    - name: Rustfmt Check
      uses: actions-rust-lang/rustfmt@v1
    - name: Run clippy
      run: cargo clippy --all -- -D warnings
    - name: Cargo Test
      run: cargo test -q
    - run: cargo build --features no_tibco_driver
    - name: merge
      if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
      run: |
        gh pr merge --merge $GITHUB_HEAD_REF
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
